# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test and Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kappes-und-bier"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: heroku plugins:install java
      - run: heroku deploy:jar build/libs/kappesundbier-0.1.0.jar --app kappes-und-bier
          #healthcheck: https://kappes-und-bier.herokuapp.com/actuator/health
          #checkstring: "UP"
          #rollbackonhealthcheckfailed: true
        #procfile: "web: java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/kappesundbier-0.1.0.jar"


